### ISSUE TITLE
Scaling Überblick

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#72]
Bei wachsenden Nutzer:innenzahlen müssen wir drüber nachdenken, inwieweit wir aktuell skalieren können. Dies ist ein Überblick über alle Issues die Skalierung betreffen.

- [ ] #62 Caching von Graphen
- [ ] #37 Flood-Limits (betrifft vor allem Signal, aber auch Telegram)
- [x] #67 Wir wissen aktuell nicht, ob ein Signal-Bericht erfolgreich gesendet wurde
- [ ] #70 Verbindung zu Signald
- [x] #71 Monitoring

Der Bot läuft auf Telegram und Threema stabil, lediglich Signal ist ein bisschen wackelig. Durch fehlendes Monitoring (#70) bekommen wir das nur manchmal mit.
